"""Compile and minify template source files into a production-ready index.html and assets."""
from __future__ import annotations

import re
from pathlib import Path


_TEMPLATES_DIR = Path(__file__).parent / "templates"


def _minify_css(css: str) -> str:
    """Remove comments and collapse whitespace in CSS."""
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.DOTALL)
    css = re.sub(r'\s+', ' ', css)
    css = re.sub(r'\s*([{};:,>~+])\s*', r'\1', css)
    css = re.sub(r';\}', '}', css)
    return css.strip()


def _minify_js(js: str) -> str:
    """Remove full-line comments and collapse blank lines in JS."""
    # Remove block comments
    js = re.sub(r'/\*.*?\*/', '', js, flags=re.DOTALL)
    # Remove full-line single-line comments (safe: leaves inline // untouched)
    js = re.sub(r'^\s*//.*$', '', js, flags=re.MULTILINE)
    # Collapse multiple blank lines
    js = re.sub(r'\n\s*\n+', '\n', js)
    # Strip trailing whitespace per line
    js = '\n'.join(line.rstrip() for line in js.split('\n'))
    return js.strip()


def _minify_html(html: str) -> str:
    """Collapse inter-tag whitespace in HTML."""
    # Remove HTML comments (preserve IE conditionals just in case)
    html = re.sub(r'<!--(?!\[if).*?-->', '', html, flags=re.DOTALL)
    # Collapse whitespace between tags
    html = re.sub(r'>\s+<', '><', html)
    # Collapse multiple spaces within text content
    html = re.sub(r' {2,}', ' ', html)
    return html.strip()


def build_html(version: str, output_assets_dir: Path) -> tuple[str, str, str]:
    """Compile template sources into minified (html, css, js) strings.

    Returns:
        (html_content, css_content, js_content) — all minified.
        The html_content references .videxer/assets/styles.css and app.js.
    """
    css = _minify_css((_TEMPLATES_DIR / "styles.css").read_text(encoding="utf-8"))
    js = _minify_js((_TEMPLATES_DIR / "app.js").read_text(encoding="utf-8"))
    html = _minify_html((_TEMPLATES_DIR / "index.html").read_text(encoding="utf-8"))
    html = f"<!-- Generated by videxer {version} -->\n{html}"
    return html, css, js
